[package]
name = "wio-blink"
version = "0.1.0"
edition = "2024"

[dependencies]
accelerometer = "0.12.0"
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embedded-graphics = "0.8.1"
heapless = "0.8.0"
microfft = "0.6.0"
micromath = "2.1.0"
nb = "1.1.0"
panic-halt = "1.0.0"
wio_terminal = "0.9.0"
